version: "3.9"

services:
  # MinIO S3-compatible storage
  minio:
    image: minio/minio
    container_name: minio_ngkafisha
    environment:
      MINIO_ROOT_USER: ${EVENT_S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${EVENT_S3_SECRET_KEY}
    ports:
      - "${MINIO_PORT:-9000}:9000"       # API (HTTP)
      - "${MINIO_CONSOLE_PORT:-9001}:9001"  # Console (HTTP)
    command: server /data --console-address ":9001"
    networks:
      - shared-net
      - default
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "${EVENT_S3_SERVICE_URL}/minio/health/live"]
      interval: 5s
      retries: 5

  minio-init:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
        mc alias set local ${EVENT_S3_SERVICE_URL_BOUNDED} ${EVENT_S3_ACCESS_KEY} ${EVENT_S3_SECRET_KEY} &&
        mc mb --ignore-existing local/${EVENT_S3_BUCKET_NAME}
      "

networks:
  shared-net:
    external: true

volumes:
  minio-data:
