version: "3.9"

services:
  # -------------------------
  # Identity Service
  # -------------------------
  identity-api:
    build:
      context: ./IdentityService
    ports:
      - "${IDENTITY_API_PORT}:8080"
    depends_on:
      identity-postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      ConnectionStrings__IdentityServiceDbContext: ${IDENTITY_DB_CONNECTION}
      Jwt__PrivateKey: ${JWT_PRIVATE_KEY}
      Jwt__PublicKey: ${JWT_PUBLIC_KEY}
      AdminCred__Email: ${ADMIN_EMAIL}
      AdminCred__Password: ${ADMIN_PASSWORD}
      IncludeDocumentationInRelease: ${INCLUDE_DOCS}

  identity-postgres:
    container_name: ${IDENTITY_DB_CONTAINER}
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${IDENTITY_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - identity-postgres-data:/var/lib/postgresql
    ports:
      - "${IDENTITY_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 2s
      timeout: 2s
      retries: 10

  # -------------------------
  # Event Service
  # -------------------------
  event-api:
    build:
      context: ./EventService/EventService.API
    ports:
      - "${EVENT_API_PORT}:8080"
    depends_on:
      event-postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    env_file:
      - .env
    environment:
      ConnectionStrings__EventServiceDbContext: ${EVENT_DB_CONNECTION}
      S3Storage__AccessKey: ${MINIO_ACCESS_KEY}
      S3Storage__SecretKey: ${MINIO_SECRET_KEY}
      S3Storage__ServiceUrl: ${MINIO_SERVICE_URL_EXTERNAL}
      S3Storage__ServiceUrlBounded: ${MINIO_SERVICE_URL_INTERNAL}
      Jwt__PublicKey: ${JWT_PUBLIC_KEY}
      IncludeDocumentationInRelease: ${INCLUDE_DOCS}

  event-postgres:
    container_name: ${EVENT_DB_CONTAINER}
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${EVENT_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - event-postgres-data:/var/lib/postgresql
    ports:
      - "${EVENT_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 2s
      timeout: 2s
      retries: 10

  # -------------------------
  # MinIO
  # -------------------------
  minio:
    image: minio/minio
    container_name: ${MINIO_CONTAINER}
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      retries: 5

  minio-init:
    image: minio/mc
    env_file:
      - .env
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
        mc alias set local ${MINIO_SERVICE_URL_INTERNAL} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY} &&
        mc mb --ignore-existing local/${MINIO_BUCKET}
      "

volumes:
  identity-postgres-data:
  event-postgres-data:
  minio-data:
